Moved file "File1.png" to "File1Test.png" 
Moved file "File2.png" to "File2Test.png" 
Moved file "File3.png" to "File3Test.png" 
Moved file "File4.png" to "File4Test.png" 
Moved file "File5.png" to "File5Test.png" 
Moved file "File6.png" to "File6Test.png" 
Unable to move file "File7.png" to "File7Test.png" for reason: "internal_api_error_AuthenticationException". 
Moved file "File8.png" to "File8Test.png" 
Moved file "File9.png" to "File9Test.png" 
Moved file "File10.png" to "File10Test.png" 

Moved file "File1Test.png" to "File1.png" 
Moved file "File2Test.png" to "File2.png" 
Moved file "File3Test.png" to "File3.png" 
Moved file "File4Test.png" to "File4.png" 
Unable to move file "File5Test.png" to "File5.png" for reason: "badtoken". 
Unable to move file "File6Test.png" to "File6.png" for reason: "badtoken". 
Moved file "File7Test.png" to "File7.png" 
Moved file "File8Test.png" to "File8.png" 
Moved file "File9Test.png" to "File9.png" 
Moved file "File10Test.png" to "File10.png" 

Moved file "File1.png" to "File1Test.png" 
Moved file "File2.png" to "File2Test.png" 
Moved file "File3.png" to "File3Test.png" 
Moved file "File4.png" to "File4Test.png" 
Unable to move file "File5.png" to "File5Test.png" for reason: "badtoken". 
Unable to move file "File6.png" to "File6Test.png" for reason: "badtoken". 
Moved file "File7.png" to "File7Test.png" 
Moved file "File8.png" to "File8Test.png" 
Moved file "File9.png" to "File9Test.png" 
Moved file "File10.png" to "File10Test.png"

Moved file "File1Test.png" to "File1.png" 
Moved file "File2Test.png" to "File2.png" 
Unable to move file "File3Test.png" to "File3.png" for reason: "internal_api_error_AuthenticationException". 
Moved file "File4Test.png" to "File4.png" 
Moved file "File5Test.png" to "File5.png" 
Moved file "File6Test.png" to "File6.png" 
Moved file "File7Test.png" to "File7.png" 
Moved file "File8Test.png" to "File8.png" 
Moved file "File9Test.png" to "File9.png" 
Unable to move file "File10Test.png" to "File10.png" for reason: "internal_api_error_AuthenticationException". 

